import { AILabel, AILabelContent, AISkeletonText, Button, Tag, Tile } from "@carbon/react";
import { useCallback } from "react";
import { type LinkOverride, MarkdownPreview } from "../notes/MarkdownPreview.tsx";
import type { AskState } from "./useAsk.ts";

interface AiAnswerProps extends AskState {
  onStop: () => void;
  onCitation: (n: number) => void;
}

const CITATION = /\[(\d+)\](?!\()/g;
const toCitationLinks = (text: string) =>
  text.replace(CITATION, (_, n: string) => `[${n}](cite:${n})`);

export function AiAnswer({
  status,
  text,
  sources,
  meta,
  errorMessage,
  retryAfterSec,
  cached,
  onStop,
  onCitation,
}: AiAnswerProps) {
  const extractive = meta?.extractive ?? false;

  const linkOverride = useCallback<LinkOverride>(
    (href, children) => {
      if (!href.startsWith("cite:")) return null;
      const n = Number(href.slice(5));
      return (
        <button
          type="button"
          className="memra-ai__citation"
          onClick={() => onCitation(n)}
          aria-label={`Source ${n}`}
        >
          {children}
        </button>
      );
    },
    [onCitation],
  );

  const loading = status === "retrieving" || status === "streaming";
  const label = (
    <AILabel
      size="xs"
      aiText="AI"
      textLabel={extractive ? "Extracted" : undefined}
      align="bottom-end"
      autoAlign
    >
      <AILabelContent>
        <p className="memra-ai__explain-title">
          {extractive ? "Extractive answer" : "Generated answer"}
        </p>
        <p className="memra-ai__explain">
          {extractive
            ? "No language model is configured, so the most relevant passages from your notes are shown verbatim."
            : `Generated by ${meta?.model ?? "a language model"} from ${sources.length} of your notes.`}
        </p>
        {sources.length > 0 && (
          <ol className="memra-ai__sources">
            {sources.map((s) => (
              <li key={s.noteId}>
                <button type="button" className="memra-ai__source" onClick={() => onCitation(s.n)}>
                  [{s.n}] {s.displayTitle}
                </button>
              </li>
            ))}
          </ol>
        )}
        <p className="memra-ai__explain">
          {meta?.local
            ? "All processing happened on your server."
            : "Your question and note excerpts were sent to a remote provider."}
          {meta &&
            !extractive &&
            " AI-generated content may be inaccurate — check the cited notes."}
        </p>
      </AILabelContent>
    </AILabel>
  );

  return (
    <Tile className="memra-ai" decorator={label}>
      {(cached || loading || text) && (
        <div className="memra-ai__head">
          {!loading && text && (
            <span className="memra-ai__title">{extractive ? "From your notes" : "Answer"}</span>
          )}
          {cached && (
            <Tag type="gray" size="sm">
              Cached
            </Tag>
          )}
          {loading && !extractive && (
            <Button kind="ghost" size="sm" onClick={onStop}>
              Stop
            </Button>
          )}
        </div>
      )}
      {loading && !text && <AISkeletonText paragraph lineCount={3} />}
      {status === "insufficient" && (
        <p className="memra-ai__note">No sufficiently related notes to answer from.</p>
      )}
      {status === "unavailable" && (
        <p className="memra-ai__note">Answers are unavailable while the search model is loading.</p>
      )}
      {status === "rate-limited" && (
        <p className="memra-ai__note">
          Too many questions in a row. Try again
          {retryAfterSec ? ` in ${retryAfterSec}s` : " shortly"}.
        </p>
      )}
      {status === "error" && (
        <p className="memra-ai__note">
          Couldn't generate an answer{errorMessage ? `: ${errorMessage}` : "."}
        </p>
      )}
      {text && (
        <MarkdownPreview
          markdown={toCitationLinks(text)}
          className="memra-ai__body"
          linkOverride={linkOverride}
        />
      )}
    </Tile>
  );
}
